services:
  app:
    image: mcr.microsoft.com/devcontainers/php:8.2
    ports:
      - "80:80"
      - "3307:3306"
    volumes:
      - .:/workspace
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=url_shortener

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=url_shortener
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
